//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CATALOGO_DETALLE
{
    public int Id { get; set; }
    public int Id_catalogo_cabecera { get; set; }
    public string Especificacion { get; set; }
    public string Nombre { get; set; }
    public int Id_padre { get; set; }
    public string Estado { get; set; }
    public System.DateTime Fc { get; set; }
    public string Uc { get; set; }
    public System.DateTime Fm { get; set; }
    public string Um { get; set; }

    public virtual CATALOGO_CABECERA CATALOGO_CABECERA { get; set; }
}
