//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class EMPLEADO
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EMPLEADO()
    {
        this.EMPLEADO_FAMILIAR = new HashSet<EMPLEADO_FAMILIAR>();
    }

    public int Id { get; set; }
    public int Id_empresa { get; set; }
    public int Id_persona { get; set; }
    public string Estado { get; set; }
    public string Email { get; set; }
    public string Telefono { get; set; }
    public System.DateTime Fc { get; set; }
    public string Uc { get; set; }
    public System.DateTime Fm { get; set; }
    public string Um { get; set; }

    public virtual EMPRESA EMPRESA { get; set; }
    public virtual PERSONA PERSONA { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EMPLEADO_FAMILIAR> EMPLEADO_FAMILIAR { get; set; }
}
