//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class EMPRESA
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EMPRESA()
    {
        this.CATALOGO_EMPRESA = new HashSet<CATALOGO_EMPRESA>();
        this.CONFIGURACION = new HashSet<CONFIGURACION>();
        this.EMPLEADO = new HashSet<EMPLEADO>();
        this.PARAMETRO = new HashSet<PARAMETRO>();
        this.PERFIL = new HashSet<PERFIL>();
    }

    public int Id { get; set; }
    public string Nombre { get; set; }
    public string Razon_social { get; set; }
    public string Ruc { get; set; }
    public string Direccion { get; set; }
    public string Telefono_1 { get; set; }
    public string Telefono_2 { get; set; }
    public string Representante_legal { get; set; }
    public string Cedula_representante_legal { get; set; }
    public string Cargo_representante_legal { get; set; }
    public int Id_Ciudad { get; set; }
    public string Estado { get; set; }
    public System.DateTime Fc { get; set; }
    public string Uc { get; set; }
    public System.DateTime Fm { get; set; }
    public string Um { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CATALOGO_EMPRESA> CATALOGO_EMPRESA { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CONFIGURACION> CONFIGURACION { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PARAMETRO> PARAMETRO { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PERFIL> PERFIL { get; set; }
}
