//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckTime.ENTITY
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CheckTimeEntities : DbContext
    {
        public CheckTimeEntities()
            : base("name=CheckTimeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATALOGO_CABECERA> CATALOGO_CABECERA { get; set; }
        public virtual DbSet<CATALOGO_DETALLE> CATALOGO_DETALLE { get; set; }
        public virtual DbSet<CATALOGO_EMPRESA> CATALOGO_EMPRESA { get; set; }
        public virtual DbSet<CONFIGURACION> CONFIGURACION { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<PARAMETRO> PARAMETRO { get; set; }
        public virtual DbSet<PERFIL> PERFIL { get; set; }
        public virtual DbSet<PERFIL_TAREA> PERFIL_TAREA { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<TAREA> TAREA { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<USUARIO_PERFIL> USUARIO_PERFIL { get; set; }
        public virtual DbSet<EMPLEADO_FAMILIAR> EMPLEADO_FAMILIAR { get; set; }
    }
}
